import { Customer } from './types';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: '1',
    name: 'Acme Corp',
    domain: 'acme.com',
    segment: 'Growth',
    contractEndDate: '2024-12-31',
    mrr: 5000,
    products: ['Air Freight', 'Customs'],
    originCountry: 'TR',
    destinationCountry: 'DE',
    status: 'Onboarding',
    accountManager: 'Alice Smith',
    lastTouchDate: '2023-10-25',
    touchedThisWeek: true,
    zohoStats: {
      openTickets: 2,
      avgResponseTimeHours: 1.5,
      avgResolutionTimeDays: 2,
      slaScore: 95,
      slaBreached: false,
      lastTicketDate: '2023-10-24',
      ticketTrend: [0, 1, 0, 2, 0, 1, 0],
    },
    onboarding: {
      startDate: '2023-10-01',
      dueDate: '2023-11-15',
      progress: 45,
      stage: 'Integration',
      bottleneck: 'Waiting for API Key from Client IT Team',
    },
    active: {
        churnRisk: 'Low',
        churnProbability: 5,
        healthScore: 88,
        satisfactionScore: 8,
        techIssues: ['Minor sync delay']
    },
    notes: 'Weekly sync completed. Technical team is engaged but slow to respond.',
  },
  {
    id: '2',
    name: 'Globex Inc',
    domain: 'globex.com',
    segment: 'Enterprise',
    contractEndDate: '2024-06-30',
    mrr: 12000,
    products: ['Ocean Freight', 'Warehousing'],
    originCountry: 'CN',
    destinationCountry: 'US',
    status: 'At Risk',
    accountManager: 'Bob Jones',
    lastTouchDate: '2023-10-10',
    touchedThisWeek: false,
    zohoStats: {
      openTickets: 8,
      avgResponseTimeHours: 12,
      avgResolutionTimeDays: 5,
      slaScore: 72,
      slaBreached: true,
      lastTicketDate: '2023-10-26',
      ticketTrend: [2, 3, 1, 4, 2, 5, 1],
    },
    onboarding: {
      startDate: '2023-06-01',
      dueDate: '2023-08-01',
      actualEndDate: '2023-08-15',
      progress: 100,
      stage: 'Completed',
    },
    active: {
      churnRisk: 'High',
      churnProbability: 75,
      healthScore: 35,
      satisfactionScore: 4,
      techIssues: ['Latency in reporting module', 'SSO Login failures'],
    },
    notes: 'Client expressed frustration regarding ongoing latency issues. Escalated to Engineering.',
  },
  {
    id: '3',
    name: 'Soylent Corp',
    domain: 'soylent.co',
    segment: 'Growth',
    contractEndDate: '2025-01-15',
    mrr: 8500,
    products: ['Road Freight'],
    originCountry: 'FR',
    destinationCountry: 'ES',
    status: 'Active',
    accountManager: 'Alice Smith',
    lastTouchDate: '2023-10-24',
    touchedThisWeek: true,
    zohoStats: {
      openTickets: 0,
      avgResponseTimeHours: 0.5,
      avgResolutionTimeDays: 0.8,
      slaScore: 99,
      slaBreached: false,
      lastTicketDate: '2023-10-15',
      ticketTrend: [0, 0, 0, 0, 1, 0, 0],
    },
    onboarding: {
      startDate: '2023-07-15',
      dueDate: '2023-09-01',
      actualEndDate: '2023-09-10',
      progress: 100,
      stage: 'Completed',
    },
    active: {
      churnRisk: 'Low',
      churnProbability: 2,
      healthScore: 92,
      satisfactionScore: 9,
      techIssues: [],
    },
    notes: 'QBR scheduled for next month. Interested in upgrading to Enterprise plan.',
  },
  {
    id: '4',
    name: 'Umbrella Pharm',
    domain: 'umbrella.com',
    segment: 'Enterprise',
    contractEndDate: '2025-09-01',
    mrr: 25000,
    products: ['Air Cold Chain', 'Pharma Logistics'],
    originCountry: 'CH',
    destinationCountry: 'US',
    status: 'Onboarding',
    accountManager: 'Charlie Day',
    lastTouchDate: '2023-10-26',
    touchedThisWeek: true,
    zohoStats: {
      openTickets: 1,
      avgResponseTimeHours: 2,
      avgResolutionTimeDays: 1,
      slaScore: 98,
      slaBreached: false,
      lastTicketDate: '2023-10-25',
      ticketTrend: [1, 0, 0, 0, 0, 1, 0],
    },
    onboarding: {
      startDate: '2023-09-15',
      dueDate: '2023-11-01',
      progress: 85,
      stage: 'Training',
    },
    active: {
        churnRisk: 'Low',
        churnProbability: 10,
        healthScore: 85,
        satisfactionScore: 8,
        techIssues: []
    },
    notes: 'Training sessions going well. Users are adopting the platform quickly.',
  },
  {
    id: '5',
    name: 'Initech',
    domain: 'initech.com',
    segment: 'SMB',
    contractEndDate: '2024-03-20',
    mrr: 3200,
    products: ['Domestic Distribution'],
    originCountry: 'US',
    destinationCountry: 'US',
    status: 'Active',
    accountManager: 'Bob Jones',
    lastTouchDate: '2023-10-18',
    touchedThisWeek: false,
    zohoStats: {
      openTickets: 1,
      avgResponseTimeHours: 4,
      avgResolutionTimeDays: 3,
      slaScore: 88,
      slaBreached: false,
      lastTicketDate: '2023-10-20',
      ticketTrend: [0, 1, 0, 0, 0, 0, 1],
    },
    onboarding: {
      startDate: '2023-08-01',
      dueDate: '2023-09-15',
      actualEndDate: '2023-09-25',
      progress: 100,
      stage: 'Completed',
    },
    active: {
      churnRisk: 'Medium',
      churnProbability: 45,
      healthScore: 65,
      satisfactionScore: 7,
      techIssues: [],
    },
    notes: 'Usage has dropped slightly in the last 2 weeks. Need to schedule a check-in.',
  },
  {
    id: '6',
    name: 'Stark Ind',
    domain: 'stark.com',
    segment: 'Enterprise',
    contractEndDate: '2026-01-01',
    mrr: 55000,
    products: ['Project Cargo', 'Ocean Freight'],
    originCountry: 'US',
    destinationCountry: 'JP',
    status: 'Active',
    accountManager: 'Tony S.',
    lastTouchDate: '2023-10-27',
    touchedThisWeek: true,
    zohoStats: {
      openTickets: 0,
      avgResponseTimeHours: 0.1,
      avgResolutionTimeDays: 0.1,
      slaScore: 100,
      slaBreached: false,
      lastTicketDate: '2023-10-22',
      ticketTrend: [0,0,0,0,0,0,0],
    },
    onboarding: {
      startDate: '2023-05-01',
      dueDate: '2023-07-15',
      actualEndDate: '2023-07-20',
      progress: 100,
      stage: 'Completed',
    },
    active: {
      churnRisk: 'Low',
      churnProbability: 1,
      healthScore: 99,
      satisfactionScore: 10,
      techIssues: [],
    },
    notes: 'Perfect health. Promoting our new AI features to them next week.',
  }
];